/**
 * Bulk-add Chef Alexis Gauthier (chefalexisgauthier.substack.com) recipes to the dishes
 * table. Scraped from the chef's Substack (ingredients + details only; steps NOT reproduced
 * — each dish backlinks its source and credits the creator, per the house convention in
 * add-schoolnightvegan-breakfast-dishes.ts).
 *
 * Titles use the dish's official French name. `aubergine-mon-amour` is intentionally
 * omitted — that post is a narrative essay with no actual recipe (no quantities / method).
 *
 * The seed is the SOURCE OF TRUTH — see scripts/seed-dish.ts. Usage:
 *   bun scripts/add-alexisgauthier-dishes.ts             # dry-run (no DB)
 *   bun scripts/add-alexisgauthier-dishes.ts --check     # dedup/report against the live DB
 *   bun scripts/add-alexisgauthier-dishes.ts --execute   # create / reconcile all
 */
import { buildDishData } from "../lib/dishes";
import { runSeed, seedModeFromArgv } from "./seed-dish";

const recipes = [
  {
    "title": "Crème Brûlée",
    "description": "A vegan take on the classic French custard dessert with a crackling caramelised sugar top.",
    "dishType": ["dessert"],
    "difficulty": 3,
    "allergens": ["soy"],
    "servings": 6,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/creme-brulee",
    "ingredients": [
      { "name": "soya milk", "quantity": 500, "unit": "g", "section": "Base Custard" },
      { "name": "plant-based cream", "quantity": 500, "unit": "g", "section": "Base Custard", "note": "such as Flora" },
      { "name": "caster sugar", "quantity": 140, "unit": "g", "section": "Base Custard" },
      { "name": "cornflour", "quantity": 40, "unit": "g", "section": "Base Custard" },
      { "name": "custard powder", "quantity": 40, "unit": "g", "section": "Base Custard" },
      { "name": "vanilla pod", "quantity": 1, "unit": "", "section": "Base Custard", "note": "infused then scraped" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Base Custard", "note": "pinch" },
      { "name": "vegan butter", "quantity": 2, "unit": "tbsp", "section": "Base Custard" },
      { "name": "demerara sugar", "quantity": 60, "unit": "g", "section": "Brûlée Topping" },
      { "name": "caster sugar", "quantity": 20, "unit": "g", "section": "Brûlée Topping" }
    ]
  },
  {
    "title": "Bourguignon de Maïtaké",
    "description": "The classic French bourguignon made the vegan way, with maitake mushrooms as the centrepiece.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": ["soy", "gluten"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/bourguignon",
    "ingredients": [
      { "name": "maitake mushrooms", "quantity": 600, "unit": "g", "section": "Mushrooms", "note": "600–800 g, kept in large clusters" },
      { "name": "soy sauce", "quantity": 3, "unit": "tbsp", "section": "First Marinade" },
      { "name": "water", "quantity": 3, "unit": "tbsp", "section": "First Marinade" },
      { "name": "brown sugar", "quantity": 1, "unit": "tbsp", "section": "First Marinade" },
      { "name": "bay leaf", "quantity": 1, "unit": "", "section": "First Marinade" },
      { "name": "olive oil", "quantity": 2, "unit": "tbsp", "section": "First Marinade" },
      { "name": "vegan dry red wine", "quantity": 500, "unit": "ml", "section": "Bourguignon Marinade" },
      { "name": "garlic", "quantity": 2, "unit": "clove", "section": "Bourguignon Marinade", "note": "crushed" },
      { "name": "bay leaf", "quantity": 1, "unit": "", "section": "Bourguignon Marinade" },
      { "name": "thyme", "quantity": 3, "unit": "sprig", "section": "Bourguignon Marinade" },
      { "name": "black pepper", "quantity": 1, "unit": "tsp", "section": "Bourguignon Marinade" },
      { "name": "carrots", "quantity": 2, "unit": "", "section": "Vegetables", "note": "large chunks" },
      { "name": "baby onions", "quantity": 200, "unit": "g", "section": "Vegetables" },
      { "name": "green cabbage", "quantity": 200, "unit": "g", "section": "Vegetables", "note": "cut into wedges" },
      { "name": "olive oil", "quantity": 2, "unit": "tbsp", "section": "Cooking" },
      { "name": "salt and pepper", "quantity": "", "unit": "", "section": "Cooking" },
      { "name": "flour", "quantity": 200, "unit": "g", "section": "Pâte Morte (sealing dough)" },
      { "name": "water", "quantity": 100, "unit": "ml", "section": "Pâte Morte (sealing dough)" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Pâte Morte (sealing dough)", "note": "pinch" },
      { "name": "mashed potatoes", "quantity": "", "unit": "", "section": "To Serve" }
    ]
  },
  {
    "title": "Faux-Gras en Terrine",
    "description": "A vegan cashew-based terrine that echoes the texture and richness of traditional foie gras.",
    "dishType": ["appetizer"],
    "difficulty": 3,
    "allergens": ["nuts", "soy", "sesame", "coconut"],
    "servings": 12,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/faux-gras-20",
    "ingredients": [
      { "name": "cashew nuts", "quantity": 900, "unit": "g", "section": "Terrine Base", "note": "soaked beforehand" },
      { "name": "cacao butter", "quantity": 180, "unit": "g", "section": "Terrine Base" },
      { "name": "neutral coconut oil", "quantity": 180, "unit": "g", "section": "Terrine Base" },
      { "name": "miso", "quantity": 80, "unit": "g", "section": "Terrine Base" },
      { "name": "soy sauce", "quantity": 2, "unit": "tbsp", "section": "Terrine Base" },
      { "name": "nutritional yeast", "quantity": 50, "unit": "g", "section": "Terrine Base" },
      { "name": "tahini", "quantity": 2, "unit": "tbsp", "section": "Terrine Base" },
      { "name": "caster sugar", "quantity": 20, "unit": "g", "section": "Terrine Base" },
      { "name": "beetroot powder", "quantity": "", "unit": "", "section": "Terrine Base", "note": "or 2 tbsp very dry beetroot purée, or 3 drops natural red food colouring" },
      { "name": "salt and pepper", "quantity": "", "unit": "", "section": "Terrine Base" },
      { "name": "cognac", "quantity": "", "unit": "", "section": "Seasoning for the \"lobes\"" },
      { "name": "port", "quantity": "", "unit": "", "section": "Seasoning for the \"lobes\"" },
      { "name": "beetroot powder", "quantity": "", "unit": "", "section": "Seasoning for the \"lobes\"", "note": "or purée, or 3 drops natural colouring" },
      { "name": "caster sugar", "quantity": 20, "unit": "g", "section": "Seasoning for the \"lobes\"" },
      { "name": "salt", "quantity": 10, "unit": "g", "section": "Seasoning for the \"lobes\"" },
      { "name": "freshly ground pepper", "quantity": "", "unit": "", "section": "Seasoning for the \"lobes\"", "note": "generously" }
    ]
  },
  {
    "title": "Tripes à la Niçoise",
    "description": "A plant-based take on the traditional Niçoise dish using tofu sheets, inspired by Restaurant Merenda in Nice.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": ["soy", "gluten"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/my-vegan-tripes-a-la-nicoise",
    "ingredients": [
      { "name": "fresh tofu sheets", "quantity": 300, "unit": "g", "section": "", "note": "yuba / bean curd sheets" },
      { "name": "carrots", "quantity": 2, "unit": "", "section": "", "note": "medium, peeled and sliced into thin rounds" },
      { "name": "onions", "quantity": 2, "unit": "", "section": "", "note": "medium, finely sliced" },
      { "name": "garlic", "quantity": 2, "unit": "clove", "section": "", "note": "minced" },
      { "name": "celery stalk", "quantity": 1, "unit": "", "section": "", "note": "finely chopped" },
      { "name": "tomato", "quantity": 1, "unit": "", "section": "", "note": "large, peeled and diced, or 150 g tinned tomatoes" },
      { "name": "potato", "quantity": 1, "unit": "", "section": "", "note": "small, peeled and roughly cut (optional, for a heartier version)" },
      { "name": "lemon zest", "quantity": 1, "unit": "", "section": "", "note": "small strip" },
      { "name": "bay leaf", "quantity": 1, "unit": "", "section": "" },
      { "name": "thyme", "quantity": "", "unit": "", "section": "", "note": "a few sprigs, or ½ tsp dried" },
      { "name": "rosemary", "quantity": 1, "unit": "sprig", "section": "", "note": "small" },
      { "name": "chili flakes", "quantity": "", "unit": "", "section": "", "note": "pinch, optional" },
      { "name": "dry white wine", "quantity": 200, "unit": "ml", "section": "" },
      { "name": "vegetable stock", "quantity": 400, "unit": "ml", "section": "" },
      { "name": "olive oil", "quantity": 2, "unit": "tbsp", "section": "" },
      { "name": "salt and black pepper", "quantity": "", "unit": "", "section": "", "note": "to taste" },
      { "name": "sourdough crust or breadcrumbs", "quantity": "", "unit": "", "section": "To finish", "note": "grated and toasted, optional" },
      { "name": "fresh parsley", "quantity": "", "unit": "", "section": "To finish", "note": "chopped" },
      { "name": "extra virgin olive oil", "quantity": "", "unit": "", "section": "To finish", "note": "a drizzle" },
      { "name": "panisses (chickpea fritters)", "quantity": "", "unit": "", "section": "To finish", "note": "to serve" }
    ]
  },
  {
    "title": "Crème Caramel",
    "description": "A baked vegan crème caramel — plant-milk custard set over a classic caramel.",
    "dishType": ["dessert"],
    "difficulty": 3,
    "allergens": ["soy", "coconut"],
    "servings": 8,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/vegan-creme-caramel",
    "ingredients": [
      { "name": "sugar", "quantity": 120, "unit": "g", "section": "For the caramel" },
      { "name": "water", "quantity": 3, "unit": "tbsp", "section": "For the caramel" },
      { "name": "soy milk", "quantity": 415, "unit": "ml", "section": "For the custard" },
      { "name": "oat milk", "quantity": 400, "unit": "ml", "section": "For the custard" },
      { "name": "sugar", "quantity": 110, "unit": "g", "section": "For the custard" },
      { "name": "cornflour", "quantity": 57, "unit": "g", "section": "For the custard", "note": "cornstarch" },
      { "name": "custard powder", "quantity": 23, "unit": "g", "section": "For the custard" },
      { "name": "coconut oil", "quantity": 70, "unit": "g", "section": "For the custard", "note": "refined" },
      { "name": "vanilla extract", "quantity": 1, "unit": "tbsp", "section": "For the custard" }
    ]
  },
  {
    "title": "Crêpe Soho au Caviar de Plantes & Beurre Blanc",
    "description": "A soft golden potato crêpe with silky shallot beurre blanc and kelp caviar.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": ["gluten", "soy"],
    "servings": 8,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/vegan-pancake",
    "ingredients": [
      { "name": "starchy potatoes", "quantity": 300, "unit": "g", "section": "For the batter" },
      { "name": "all-purpose flour", "quantity": 50, "unit": "g", "section": "For the batter" },
      { "name": "cornstarch", "quantity": 10, "unit": "g", "section": "For the batter" },
      { "name": "salt", "quantity": "1/2", "unit": "tsp", "section": "For the batter" },
      { "name": "baking powder", "quantity": "1/2", "unit": "tsp", "section": "For the batter" },
      { "name": "unsweetened oat or soy milk", "quantity": 200, "unit": "ml", "section": "For the batter" },
      { "name": "vegan butter or neutral oil", "quantity": 25, "unit": "g", "section": "For the batter" },
      { "name": "nutmeg", "quantity": "", "unit": "", "section": "For the batter", "note": "pinch" },
      { "name": "shallots", "quantity": 2, "unit": "", "section": "For the vegan beurre blanc", "note": "small, about 60 g" },
      { "name": "dry white wine", "quantity": 120, "unit": "ml", "section": "For the vegan beurre blanc" },
      { "name": "white wine or champagne vinegar", "quantity": 30, "unit": "ml", "section": "For the vegan beurre blanc" },
      { "name": "cold vegan butter", "quantity": 115, "unit": "g", "section": "For the vegan beurre blanc" },
      { "name": "oat or soy cream", "quantity": 30, "unit": "ml", "section": "For the vegan beurre blanc", "note": "optional" },
      { "name": "sea salt", "quantity": "1/2", "unit": "tsp", "section": "For the vegan beurre blanc" },
      { "name": "ground white pepper", "quantity": "", "unit": "", "section": "For the vegan beurre blanc", "note": "pinch" },
      { "name": "fresh lemon juice", "quantity": 2, "unit": "ml", "section": "For the vegan beurre blanc", "note": "2–3 ml" }
    ]
  },
  {
    "title": "Ratatouille",
    "description": "A Provençal vegetable stew of individually sautéed summer vegetables, rested before serving.",
    "dishType": ["main", "side"],
    "difficulty": 2,
    "allergens": [],
    "servings": 6,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/ratatouille",
    "ingredients": [
      { "name": "aubergines", "quantity": 2, "unit": "", "section": "", "note": "medium, cut into 2–3 cm chunks" },
      { "name": "courgettes", "quantity": 2, "unit": "", "section": "", "note": "sliced into thick half-moons" },
      { "name": "yellow pepper", "quantity": 1, "unit": "", "section": "", "note": "large, cut into bite-sized strips" },
      { "name": "ripe tomatoes", "quantity": 4, "unit": "", "section": "", "note": "peeled and chopped, or 300 ml passata" },
      { "name": "onion", "quantity": 1, "unit": "", "section": "", "note": "large, finely sliced" },
      { "name": "fresh basil leaves", "quantity": "", "unit": "", "section": "", "note": "a handful" },
      { "name": "thyme", "quantity": "", "unit": "", "section": "", "note": "a few sprigs" },
      { "name": "olive oil", "quantity": "", "unit": "", "section": "", "note": "generously" },
      { "name": "salt and freshly ground black pepper", "quantity": "", "unit": "", "section": "" }
    ]
  },
  {
    "title": "Tortellini Verts, Champignons Marinés & Bouillon de Petits Pois",
    "description": "Gluten-free rice-flour tortellini with a lovage-and-greens filling, pickled mushrooms and a light pea broth.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": [],
    "possibleAllergens": ["nuts"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/lovage-mon-amour-de-printemps",
    "ingredients": [
      { "name": "fine white rice flour", "quantity": 150, "unit": "g", "section": "Rice Flour Tortellini Dough", "note": "plus more for dusting" },
      { "name": "tapioca starch", "quantity": 50, "unit": "g", "section": "Rice Flour Tortellini Dough" },
      { "name": "salt", "quantity": "1/2", "unit": "tsp", "section": "Rice Flour Tortellini Dough" },
      { "name": "olive oil", "quantity": 2, "unit": "tbsp", "section": "Rice Flour Tortellini Dough" },
      { "name": "hot water", "quantity": 120, "unit": "ml", "section": "Rice Flour Tortellini Dough", "note": "120–130 ml, not boiling" },
      { "name": "baby spinach", "quantity": 100, "unit": "g", "section": "Spinach, Wild Rocket & Lovage Filling" },
      { "name": "wild rocket", "quantity": 100, "unit": "g", "section": "Spinach, Wild Rocket & Lovage Filling" },
      { "name": "fresh lovage leaves", "quantity": 10, "unit": "g", "section": "Spinach, Wild Rocket & Lovage Filling", "note": "or substitute celery leaf + parsley" },
      { "name": "olive oil", "quantity": 1, "unit": "tbsp", "section": "Spinach, Wild Rocket & Lovage Filling" },
      { "name": "garlic", "quantity": 1, "unit": "clove", "section": "Spinach, Wild Rocket & Lovage Filling", "note": "finely minced" },
      { "name": "plant cheese", "quantity": 3, "unit": "tbsp", "section": "Spinach, Wild Rocket & Lovage Filling", "note": "our own" },
      { "name": "salt and black pepper", "quantity": "", "unit": "", "section": "Spinach, Wild Rocket & Lovage Filling", "note": "to taste" },
      { "name": "wild mushrooms", "quantity": 100, "unit": "g", "section": "Pickled Mushrooms", "note": "chanterelle, oyster or shimeji, cleaned and halved" },
      { "name": "white wine vinegar", "quantity": 100, "unit": "ml", "section": "Pickled Mushrooms" },
      { "name": "water", "quantity": 50, "unit": "ml", "section": "Pickled Mushrooms" },
      { "name": "maple syrup", "quantity": 1, "unit": "tbsp", "section": "Pickled Mushrooms" },
      { "name": "thyme", "quantity": 1, "unit": "sprig", "section": "Pickled Mushrooms" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Pickled Mushrooms", "note": "pinch" },
      { "name": "pea pods", "quantity": 500, "unit": "g", "section": "Light Pea Broth" },
      { "name": "vegetable stock", "quantity": 500, "unit": "ml", "section": "Light Pea Broth", "note": "preferably clear and light" },
      { "name": "shallot", "quantity": 1, "unit": "", "section": "Light Pea Broth", "note": "small, finely chopped" },
      { "name": "olive oil", "quantity": 1, "unit": "tbsp", "section": "Light Pea Broth" },
      { "name": "lovage leaves", "quantity": "", "unit": "", "section": "Light Pea Broth", "note": "plenty" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Light Pea Broth", "note": "to taste" }
    ]
  },
  {
    "title": "Bouillabaisse de Marseille",
    "description": "A plant-based recreation of the iconic Marseille bouillabaisse with a seaweed broth, saffron, fennel and Pastis.",
    "dishType": ["soup", "main"],
    "difficulty": 3,
    "allergens": ["soy"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/mediterranean-sea-in-a-pot",
    "ingredients": [
      { "name": "green algae (Caulerpa)", "quantity": 100, "unit": "g", "section": "For the seaweed broth" },
      { "name": "nori leaves", "quantity": 100, "unit": "g", "section": "For the seaweed broth" },
      { "name": "red dulse", "quantity": 100, "unit": "g", "section": "For the seaweed broth" },
      { "name": "Irish kombu", "quantity": 100, "unit": "g", "section": "For the seaweed broth" },
      { "name": "potato", "quantity": 100, "unit": "g", "section": "Main ingredients" },
      { "name": "aniseed", "quantity": 1, "unit": "", "section": "Main ingredients" },
      { "name": "shallot", "quantity": 1, "unit": "", "section": "Main ingredients", "note": "small" },
      { "name": "leek", "quantity": "1/2", "unit": "", "section": "Main ingredients", "note": "chopped roughly" },
      { "name": "carrot", "quantity": "1/2", "unit": "", "section": "Main ingredients", "note": "chopped roughly" },
      { "name": "lentils", "quantity": 50, "unit": "g", "section": "Main ingredients", "note": "raw" },
      { "name": "saffron", "quantity": 2, "unit": "g", "section": "Main ingredients" },
      { "name": "Pastis", "quantity": 8, "unit": "cl", "section": "Main ingredients" },
      { "name": "fennel", "quantity": "1/2", "unit": "", "section": "Main ingredients", "note": "bulb" },
      { "name": "white wine", "quantity": 20, "unit": "cl", "section": "Main ingredients" },
      { "name": "concentrated tomato", "quantity": 1, "unit": "tbsp", "section": "Main ingredients" },
      { "name": "bay leaves", "quantity": 2, "unit": "", "section": "Main ingredients" },
      { "name": "plant cream", "quantity": 20, "unit": "cl", "section": "Main ingredients" },
      { "name": "olive oil", "quantity": "", "unit": "", "section": "Main ingredients" }
    ]
  },
  {
    "title": "Barbajuan d'Hiver",
    "description": "A winter version of the Niçois fried turnover, filled with swiss chard and greens.",
    "dishType": ["appetizer", "snack"],
    "difficulty": 3,
    "allergens": ["gluten"],
    "possibleAllergens": ["nuts"],
    "servings": 20,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/swiss-chard",
    "ingredients": [
      { "name": "all-purpose flour", "quantity": 250, "unit": "g", "section": "Dough" },
      { "name": "water", "quantity": 90, "unit": "g", "section": "Dough", "note": "6–8 tbsp" },
      { "name": "olive oil", "quantity": 30, "unit": "g", "section": "Dough", "note": "2–4 tbsp" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Dough", "note": "a pinch" },
      { "name": "white wine vinegar", "quantity": "", "unit": "", "section": "Dough", "note": "a couple of drops" },
      { "name": "spinach", "quantity": 150, "unit": "g", "section": "Filling", "note": "pan fried, cooked and squeezed dry" },
      { "name": "swiss chard", "quantity": 100, "unit": "g", "section": "Filling", "note": "pan fried, cooked and squeezed dry" },
      { "name": "leek", "quantity": 1, "unit": "", "section": "Filling", "note": "small, white part only, finely chopped" },
      { "name": "onion", "quantity": 1, "unit": "", "section": "Filling", "note": "small, finely diced" },
      { "name": "garlic", "quantity": 2, "unit": "clove", "section": "Filling", "note": "minced" },
      { "name": "Superstraccia", "quantity": 120, "unit": "g", "section": "Filling", "note": "from Julienne Bruno" },
      { "name": "fresh parsley", "quantity": 1, "unit": "tbsp", "section": "Filling", "note": "chopped" },
      { "name": "fresh thyme leaves", "quantity": 1, "unit": "tsp", "section": "Filling" },
      { "name": "salt and black pepper", "quantity": "", "unit": "", "section": "Filling", "note": "to taste" },
      { "name": "olive oil", "quantity": "", "unit": "", "section": "Filling", "note": "for sautéing" },
      { "name": "neutral oil", "quantity": "", "unit": "", "section": "For Frying", "note": "vegetable or sunflower" }
    ]
  },
  {
    "title": "Navets au Foin, Asperges Vertes & Morilles à la Crème",
    "description": "Whole turnips roasted with hay and maple, with green asparagus and a creamed morel sauce.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": ["soy"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/turnip",
    "ingredients": [
      { "name": "turnips", "quantity": 4, "unit": "", "section": "Hay-Infused Turnips", "note": "scrubbed, tops trimmed" },
      { "name": "food-grade hay", "quantity": 2, "unit": "cup", "section": "Hay-Infused Turnips", "note": "rinsed" },
      { "name": "plant-based butter", "quantity": 4, "unit": "tbsp", "section": "Hay-Infused Turnips", "note": "unsalted" },
      { "name": "maple syrup", "quantity": 4, "unit": "tbsp", "section": "Hay-Infused Turnips" },
      { "name": "sea salt", "quantity": 1, "unit": "tsp", "section": "Hay-Infused Turnips" },
      { "name": "olive oil", "quantity": "", "unit": "", "section": "Hay-Infused Turnips", "note": "for searing" },
      { "name": "green asparagus", "quantity": 8, "unit": "", "section": "Green Asparagus", "note": "thick, woody ends trimmed" },
      { "name": "olive oil", "quantity": 1, "unit": "tbsp", "section": "Green Asparagus" },
      { "name": "vegetable broth", "quantity": 2, "unit": "cup", "section": "Green Asparagus" },
      { "name": "flaky sea salt and black pepper", "quantity": "", "unit": "", "section": "Green Asparagus" },
      { "name": "fresh morels", "quantity": 1, "unit": "cup", "section": "Creamed Morels" },
      { "name": "shallot", "quantity": 1, "unit": "", "section": "Creamed Morels", "note": "finely chopped" },
      { "name": "garlic", "quantity": 1, "unit": "clove", "section": "Creamed Morels", "note": "minced" },
      { "name": "plant cream", "quantity": "1/2", "unit": "cup", "section": "Creamed Morels" },
      { "name": "Cognac", "quantity": 2, "unit": "tbsp", "section": "Creamed Morels" },
      { "name": "fresh thyme leaves", "quantity": 1, "unit": "tsp", "section": "Creamed Morels" },
      { "name": "salt and pepper", "quantity": "", "unit": "", "section": "Creamed Morels", "note": "to taste" }
    ]
  },
  {
    "title": "Pétales d'Oignon Marinés, Crescendo d'Algues & Bouillon Clair Breton",
    "description": "Sweet-and-tangy marinated onion petals paired with a crescendo of seaweed and a delicate Breton clear sea broth.",
    "dishType": ["appetizer", "soup"],
    "difficulty": 3,
    "allergens": ["soy", "sesame"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/onion",
    "ingredients": [
      { "name": "white onions", "quantity": 2, "unit": "", "section": "For the Marinated Onion Petals", "note": "large, peeled and cut into thin petals" },
      { "name": "rice vinegar", "quantity": "1/4", "unit": "cup", "section": "For the Marinated Onion Petals" },
      { "name": "maple syrup", "quantity": 1, "unit": "tbsp", "section": "For the Marinated Onion Petals" },
      { "name": "smoked paprika", "quantity": 1, "unit": "tsp", "section": "For the Marinated Onion Petals" },
      { "name": "sea salt", "quantity": "1/2", "unit": "tsp", "section": "For the Marinated Onion Petals" },
      { "name": "black pepper", "quantity": "1/4", "unit": "tsp", "section": "For the Marinated Onion Petals" },
      { "name": "mixed dried seaweed", "quantity": 1, "unit": "cup", "section": "For the Crescendo of Seaweed", "note": "such as wakame, dulse and nori" },
      { "name": "sesame oil", "quantity": 1, "unit": "tbsp", "section": "For the Crescendo of Seaweed" },
      { "name": "tamari or soy sauce", "quantity": 1, "unit": "tsp", "section": "For the Crescendo of Seaweed" },
      { "name": "rice vinegar", "quantity": 1, "unit": "tsp", "section": "For the Crescendo of Seaweed" },
      { "name": "sesame seeds", "quantity": 1, "unit": "tsp", "section": "For the Crescendo of Seaweed" },
      { "name": "vegetable stock", "quantity": 1, "unit": "l", "section": "For the Breton Clear Sea Broth" },
      { "name": "leek", "quantity": 1, "unit": "", "section": "For the Breton Clear Sea Broth", "note": "cleaned and roughly chopped" },
      { "name": "fennel bulb", "quantity": 1, "unit": "", "section": "For the Breton Clear Sea Broth", "note": "roughly chopped" },
      { "name": "garlic", "quantity": 2, "unit": "clove", "section": "For the Breton Clear Sea Broth", "note": "smashed" },
      { "name": "fresh Brittany kombu seaweed", "quantity": 1, "unit": "cup", "section": "For the Breton Clear Sea Broth" },
      { "name": "fresh thyme", "quantity": 1, "unit": "sprig", "section": "For the Breton Clear Sea Broth" },
      { "name": "bay leaf", "quantity": 1, "unit": "", "section": "For the Breton Clear Sea Broth" },
      { "name": "black peppercorns", "quantity": 1, "unit": "tsp", "section": "For the Breton Clear Sea Broth" },
      { "name": "toasted sesame seeds", "quantity": "", "unit": "", "section": "For Garnish" }
    ]
  },
  {
    "title": "Île Flottante",
    "description": "A vegan take on the classic French dessert — aquafaba meringue islands floating on crème anglaise with caramel.",
    "dishType": ["dessert"],
    "difficulty": 3,
    "allergens": ["soy"],
    "servings": 6,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/a-vegan-floating-island",
    "ingredients": [
      { "name": "aquafaba", "quantity": 300, "unit": "g", "section": "Aquafaba \"Meringue\" Islands", "note": "chickpea liquid, reduced to 100 g" },
      { "name": "cornflour", "quantity": 15, "unit": "g", "section": "Aquafaba \"Meringue\" Islands" },
      { "name": "icing sugar", "quantity": 100, "unit": "g", "section": "Aquafaba \"Meringue\" Islands" },
      { "name": "sugar", "quantity": 70, "unit": "g", "section": "Aquafaba \"Meringue\" Islands" },
      { "name": "vinegar", "quantity": 1, "unit": "tbsp", "section": "Aquafaba \"Meringue\" Islands", "note": "1 spoon" },
      { "name": "salt", "quantity": "", "unit": "", "section": "Aquafaba \"Meringue\" Islands", "note": "pinch" },
      { "name": "Flora cream", "quantity": 200, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "oat milk", "quantity": 200, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "soy milk", "quantity": 100, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "sugar", "quantity": 70, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "cornflour", "quantity": 20, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "vegan custard powder", "quantity": 30, "unit": "g", "section": "Vegan Crème Anglaise" },
      { "name": "vanilla pod", "quantity": 1, "unit": "", "section": "Vegan Crème Anglaise" },
      { "name": "caster sugar", "quantity": 100, "unit": "g", "section": "Caramel Dome" },
      { "name": "water", "quantity": "", "unit": "", "section": "Caramel Dome", "note": "just enough to wet sugar" },
      { "name": "oil", "quantity": "", "unit": "", "section": "Caramel Dome", "note": "for greasing moulds" }
    ]
  },
  {
    "title": "Soupe VGE",
    "description": "A vegan homage to Bocuse's Soupe VGE — roasted concentrated broth, glazed vegetables with morels, faux gras and truffle under a puff-pastry seal.",
    "dishType": ["soup"],
    "difficulty": 3,
    "allergens": ["gluten", "soy", "nuts"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/soupe-vge",
    "ingredients": [
      { "name": "onion", "quantity": 300, "unit": "g", "section": "Roasted Concentrated Vegetable Broth" },
      { "name": "carrot", "quantity": 250, "unit": "g", "section": "Roasted Concentrated Vegetable Broth" },
      { "name": "celeriac", "quantity": 250, "unit": "g", "section": "Roasted Concentrated Vegetable Broth" },
      { "name": "beetroot", "quantity": 150, "unit": "g", "section": "Roasted Concentrated Vegetable Broth" },
      { "name": "water", "quantity": 2500, "unit": "g", "section": "Roasted Concentrated Vegetable Broth" },
      { "name": "carrot", "quantity": 120, "unit": "g", "section": "Garnish Base", "note": "small dice" },
      { "name": "celeriac", "quantity": 400, "unit": "g", "section": "Garnish Base", "note": "small dice" },
      { "name": "morels", "quantity": 80, "unit": "g", "section": "Garnish Base", "note": "fresh or rehydrated" },
      { "name": "olive oil", "quantity": 30, "unit": "g", "section": "Garnish Base" },
      { "name": "concentrated broth", "quantity": 200, "unit": "g", "section": "Garnish Base" },
      { "name": "salt", "quantity": 5, "unit": "g", "section": "Garnish Base" },
      { "name": "cooked garnish", "quantity": 120, "unit": "g", "section": "Assembly (Per Bowl)", "note": "approx" },
      { "name": "concentrated broth", "quantity": 180, "unit": "g", "section": "Assembly (Per Bowl)", "note": "180–200 g, hot" },
      { "name": "vegan vermouth", "quantity": 15, "unit": "g", "section": "Assembly (Per Bowl)", "note": "15–20 g" },
      { "name": "Gauthier vegan faux gras", "quantity": 60, "unit": "g", "section": "Assembly (Per Bowl)", "note": "60–70 g" },
      { "name": "black truffle", "quantity": 3, "unit": "g", "section": "Assembly (Per Bowl)", "note": "3–5 g" },
      { "name": "vegan puff pastry", "quantity": 75, "unit": "g", "section": "Puff Pastry Seal with Umami Glaze", "note": "approx" },
      { "name": "white miso", "quantity": 10, "unit": "g", "section": "Puff Pastry Seal with Umami Glaze" },
      { "name": "soy sauce", "quantity": 10, "unit": "g", "section": "Puff Pastry Seal with Umami Glaze" },
      { "name": "olive oil", "quantity": 15, "unit": "g", "section": "Puff Pastry Seal with Umami Glaze" }
    ]
  },
  {
    "title": "Blanquette de Tofu",
    "description": "A classic French blanquette reimagined with tofu and vegetables in a creamy plant-based sauce.",
    "dishType": ["main"],
    "difficulty": 3,
    "allergens": ["soy", "gluten"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/vegan-blanquette-with-soft-tofu",
    "ingredients": [
      { "name": "firm tofu", "quantity": 400, "unit": "g", "section": "Main", "note": "frozen, pressed then thawed" },
      { "name": "carrots", "quantity": 2, "unit": "", "section": "Main", "note": "sliced diagonally" },
      { "name": "leek", "quantity": 1, "unit": "", "section": "Main", "note": "white part only, cut into chunks" },
      { "name": "mushrooms", "quantity": 150, "unit": "g", "section": "Main", "note": "150–200 g, halved" },
      { "name": "shallot", "quantity": 1, "unit": "", "section": "Main", "note": "small, finely chopped" },
      { "name": "light vegetable stock", "quantity": 700, "unit": "ml", "section": "Main" },
      { "name": "bay leaf", "quantity": 1, "unit": "", "section": "Main" },
      { "name": "thyme", "quantity": 1, "unit": "sprig", "section": "Main" },
      { "name": "olive oil", "quantity": 1, "unit": "tbsp", "section": "Main" },
      { "name": "plant-based cream", "quantity": 150, "unit": "ml", "section": "Sauce", "note": "soy recommended" },
      { "name": "vegan butter", "quantity": 1, "unit": "tbsp", "section": "Sauce" },
      { "name": "flour", "quantity": 1, "unit": "tsp", "section": "Sauce" },
      { "name": "Dijon mustard", "quantity": 1, "unit": "tsp", "section": "Sauce" },
      { "name": "lemon juice", "quantity": "1/2", "unit": "", "section": "Sauce", "note": "juice of ½ lemon" },
      { "name": "nutritional yeast", "quantity": 1, "unit": "tsp", "section": "Sauce" },
      { "name": "fresh parsley", "quantity": "", "unit": "", "section": "To serve", "note": "finely chopped" },
      { "name": "salt and white pepper", "quantity": "", "unit": "", "section": "To serve" }
    ]
  },
  {
    "title": "Bisque au Cœur de Palmier",
    "description": "A vegan take on the great French bisque — a rich seaweed-broth soup finished with brown-butter hearts of palm.",
    "dishType": ["soup"],
    "difficulty": 3,
    "allergens": ["soy"],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/lobster-bisque-with-no-lobster",
    "ingredients": [
      { "name": "Irish moss", "quantity": 10, "unit": "g", "section": "Seaweed Broth" },
      { "name": "dried wakame", "quantity": 10, "unit": "g", "section": "Seaweed Broth" },
      { "name": "sea lettuce", "quantity": 10, "unit": "g", "section": "Seaweed Broth" },
      { "name": "thong weed", "quantity": 10, "unit": "g", "section": "Seaweed Broth" },
      { "name": "sugar kelp", "quantity": 10, "unit": "g", "section": "Seaweed Broth" },
      { "name": "water", "quantity": 2, "unit": "l", "section": "Seaweed Broth" },
      { "name": "fennel bulbs", "quantity": 2, "unit": "", "section": "Bisque", "note": "finely sliced" },
      { "name": "onions", "quantity": 2, "unit": "", "section": "Bisque", "note": "large, finely sliced" },
      { "name": "celery stalk", "quantity": 1, "unit": "", "section": "Bisque", "note": "sliced" },
      { "name": "tomato paste", "quantity": 50, "unit": "g", "section": "Bisque" },
      { "name": "Cognac", "quantity": 75, "unit": "ml", "section": "Bisque" },
      { "name": "saffron", "quantity": "", "unit": "", "section": "Bisque", "note": "1 pinch" },
      { "name": "white miso", "quantity": 1, "unit": "tbsp", "section": "Bisque" },
      { "name": "oat cream", "quantity": 150, "unit": "ml", "section": "Bisque" },
      { "name": "plant-based butter", "quantity": 30, "unit": "g", "section": "Bisque" },
      { "name": "seaweed broth", "quantity": "1.5", "unit": "l", "section": "Bisque" },
      { "name": "bay leaves", "quantity": 2, "unit": "", "section": "Bisque" },
      { "name": "black peppercorns", "quantity": 1, "unit": "tsp", "section": "Bisque" },
      { "name": "sea salt", "quantity": "", "unit": "", "section": "Bisque", "note": "to taste" },
      { "name": "hearts of palm", "quantity": 2, "unit": "", "section": "Brown Butter Heart of Palm", "note": "large" },
      { "name": "plant-based butter", "quantity": 40, "unit": "g", "section": "Brown Butter Heart of Palm" },
      { "name": "olive oil", "quantity": 1, "unit": "tbsp", "section": "Brown Butter Heart of Palm" },
      { "name": "fleur de sel", "quantity": "", "unit": "", "section": "Brown Butter Heart of Palm" }
    ]
  },
  {
    "title": "Brioche",
    "description": "The chef's vegan brioche — an enriched plant-based dough with a classic brioche crumb.",
    "dishType": ["breakfast", "dessert"],
    "difficulty": 3,
    "allergens": ["gluten", "soy"],
    "servings": 12,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/brioche-recipe",
    "ingredients": [
      { "name": "strong white bread flour", "quantity": 400, "unit": "g", "section": "" },
      { "name": "plant milk", "quantity": 200, "unit": "g", "section": "", "note": "soy milk" },
      { "name": "vegan butter", "quantity": 170, "unit": "g", "section": "", "note": "softened" },
      { "name": "caster sugar", "quantity": 80, "unit": "g", "section": "" },
      { "name": "fine sea salt", "quantity": 14, "unit": "g", "section": "" },
      { "name": "fresh yeast", "quantity": 12, "unit": "g", "section": "" },
      { "name": "vegetable oil", "quantity": 40, "unit": "g", "section": "" }
    ]
  },
  {
    "title": "Panisse",
    "description": "Provençal chickpea fries — creamy chickpea dough set, sliced and seared crisp in olive oil.",
    "dishType": ["side", "snack"],
    "difficulty": 2,
    "allergens": [],
    "servings": 4,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/thank-you-panisse",
    "ingredients": [
      { "name": "chickpea flour", "quantity": 250, "unit": "g", "section": "", "note": "farine de pois chiches" },
      { "name": "water", "quantity": 1, "unit": "l", "section": "" },
      { "name": "olive oil", "quantity": 2, "unit": "tbsp", "section": "", "note": "plus extra for frying" },
      { "name": "salt", "quantity": 1, "unit": "tsp", "section": "" },
      { "name": "freshly ground black pepper", "quantity": "", "unit": "", "section": "", "note": "optional" }
    ]
  },
  {
    "title": "Fromage de Cajou aux Herbes de Provence",
    "description": "A fresh cashew cheese infused with rosemary and thyme, preserved in olive oil.",
    "dishType": ["appetizer", "snack"],
    "difficulty": 2,
    "allergens": ["nuts"],
    "servings": 8,
    "resourceLink": "https://chefalexisgauthier.substack.com/p/the-redemption-of-vegan-cheese",
    "ingredients": [
      { "name": "raw cashew nuts", "quantity": 225, "unit": "g", "section": "Cheese base" },
      { "name": "lemon juice", "quantity": 30, "unit": "g", "section": "Cheese base", "note": "30–45 g" },
      { "name": "apple cider vinegar", "quantity": 15, "unit": "g", "section": "Cheese base" },
      { "name": "garlic", "quantity": 1, "unit": "clove", "section": "Cheese base", "note": "1–2 cloves (5–10 g)" },
      { "name": "salt", "quantity": 5, "unit": "g", "section": "Cheese base" },
      { "name": "water", "quantity": 30, "unit": "ml", "section": "Cheese base", "note": "30–60 ml" },
      { "name": "nutritional yeast", "quantity": 7, "unit": "g", "section": "Cheese base" },
      { "name": "fresh rosemary", "quantity": 5, "unit": "g", "section": "Herb crust", "note": "finely chopped" },
      { "name": "fresh thyme", "quantity": 5, "unit": "g", "section": "Herb crust", "note": "finely chopped" },
      { "name": "cracked black pepper", "quantity": 2, "unit": "g", "section": "Herb crust", "note": "optional" },
      { "name": "extra virgin olive oil", "quantity": 250, "unit": "ml", "section": "Preserving", "note": "250–300 ml" },
      { "name": "rosemary and thyme sprigs", "quantity": "", "unit": "", "section": "Preserving", "note": "fresh" }
    ]
  }
];

const mode = seedModeFromArgv(process.argv.slice(2));
for (const r of recipes) {
  const dishData = buildDishData({ ...r, cuisines: ["french"], originalCreator: "Alexis Gauthier" });
  await runSeed(dishData.title as string, dishData, mode);
}
